'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="VbCal")>  _
Partial Public Class DataClasses1DataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.CapstoneProjectVB.My.MySettings.Default.VbCalConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.StoredProcedure2")>  _
	Public Function StoredProcedure2(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal param1 As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Date")> ByVal param2 As System.Nullable(Of Date)) As ISingleResult(Of StoredProcedure2Result)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), param1, param2)
		Return CType(result.ReturnValue,ISingleResult(Of StoredProcedure2Result))
	End Function
End Class

Partial Public Class StoredProcedure2Result
	
	Private _Date As Date
	
	Private _DayOfYear As Integer
	
	Private _Day As Integer
	
	Private _Week As Integer
	
	Private _Month As Integer
	
	Private _Year As Integer
	
	Private _KindOfDay As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="Date", Storage:="_Date", DbType:="DateTime NOT NULL")>  _
	Public Property [Date]() As Date
		Get
			Return Me._Date
		End Get
		Set
			If ((Me._Date = value)  _
						= false) Then
				Me._Date = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DayOfYear", DbType:="Int NOT NULL")>  _
	Public Property DayOfYear() As Integer
		Get
			Return Me._DayOfYear
		End Get
		Set
			If ((Me._DayOfYear = value)  _
						= false) Then
				Me._DayOfYear = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Day", DbType:="Int NOT NULL")>  _
	Public Property Day() As Integer
		Get
			Return Me._Day
		End Get
		Set
			If ((Me._Day = value)  _
						= false) Then
				Me._Day = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Week", DbType:="Int NOT NULL")>  _
	Public Property Week() As Integer
		Get
			Return Me._Week
		End Get
		Set
			If ((Me._Week = value)  _
						= false) Then
				Me._Week = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Month", DbType:="Int NOT NULL")>  _
	Public Property Month() As Integer
		Get
			Return Me._Month
		End Get
		Set
			If ((Me._Month = value)  _
						= false) Then
				Me._Month = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Year", DbType:="Int NOT NULL")>  _
	Public Property Year() As Integer
		Get
			Return Me._Year
		End Get
		Set
			If ((Me._Year = value)  _
						= false) Then
				Me._Year = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KindOfDay", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property KindOfDay() As String
		Get
			Return Me._KindOfDay
		End Get
		Set
			If (String.Equals(Me._KindOfDay, value) = false) Then
				Me._KindOfDay = value
			End If
		End Set
	End Property
End Class
